# This file controls how Fivetran runs your transformation scripts. 
# For each transform, include the name of the file, what type of trigger, and trigger details. 
# Trigger options are 1. table (transformation will run when fresh data arrives from Fivetran) 
#                  or 2. interval (transformation will run on a set time schedule)
# Use three dashes (“---”) to separate transform configurations
# See examples below

#name: mysql_transform_simple.sql #transformation file name goes here
#trigger: 
#  type: table 
#  tables: #list the tables that will trigger this transformation
#    - schema.table
#    - schema2.table2
# ---

name: salesforcetransform.sql
trigger: 
  type: interval
  interval: 24h #choose from 5m, 15m, 30m, 1h, 2h, 3h, 6h, 8h, 12h, 24h
  
---
  
name: snowflakes3transform.sql
trigger: 
  type: table
  tables: #list the tables that will trigger this transformation
    - SFMC.ACTIVITY
